### PR TITLE
fix missing name key

### PR DESCRIPTION
**Pull request by ahmadia**

### CODE REVIEW

**Comment by arokem** [comment]
Thanks! Will this fix the conda/pip issue, or is this unrelated?

**Comment by ahmadia** [comment]
Yes, this is the problem.

**Comment by ahmadia** [comment]
https://github.com/conda/conda-env/issues/168

**Comment by arokem** [comment]
Cool - thanks for investigating!

**Comment by arokem** [comment]
Sadly, @binder-project still fails to build this one. Will wait for the logging interface to come online to investigate more closely...

**Comment by ahmadia** [comment]
binder-project is still down :)

**Comment by arokem** [comment]
Ah yes - that explains! Looking forward to trying this out soon. Thanks
again!

**Pull request merged**
